name: Bug Report
description: Report a bug or unexpected behavior in the project
title: "[Bug] <short summary>"
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below as clearly as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What are the exact steps to reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: You can also drag and drop images here.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Include OS, browser, Node version, or any relevant context.
      placeholder: e.g., macOS 14, Chrome 125, Node 20.3.1

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or logs about the problem here.
